version: '2'
services:
  broker:
    image: rabbitmq:3
  mysql:
    image: mysql
    volumes:
      - /Users/dmsiegel/storage:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
  gateway:
    build: ../sample-gateway
    ports:
      - "8081:8080"
    links:
      - broker:broker
    depends_on:
      - broker
  auth:
    build: ../sample-auth-service
    links:
      - broker:broker
      - mysql
    depends_on:
      - mysql
      - broker
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - gateway
